variable "aws_region" {
  description = "AWS Region for staging."
  type        = string
  default     = "eu-central-1"
}

variable "name_prefix" {
  description = "Lowercase prefix used for resource names and globally unique bucket names."
  type        = string
  default     = "gen-automation-staging"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,29}$", var.name_prefix))
    error_message = "name_prefix must be 3-30 lowercase letters, digits, or hyphens."
  }
}

variable "vpc_cidr" {
  description = "Staging VPC IPv4 range."
  type        = string
  default     = "10.42.0.0/16"
}

variable "public_subnet_cidr" {
  description = "Public control-plane subnet IPv4 range."
  type        = string
  default     = "10.42.0.0/24"
}

variable "private_subnet_a_cidr" {
  description = "First private RDS subnet IPv4 range."
  type        = string
  default     = "10.42.10.0/24"
}

variable "private_subnet_b_cidr" {
  description = "Second private RDS subnet IPv4 range."
  type        = string
  default     = "10.42.11.0/24"
}

variable "http_ingress_cidrs" {
  description = "IPv4 clients allowed to reach public HTTP and HTTPS. SSH is never opened."
  type        = set(string)
  default     = ["0.0.0.0/0"]

  validation {
    condition     = length(var.http_ingress_cidrs) > 0
    error_message = "At least one HTTP/HTTPS ingress CIDR is required."
  }
}

variable "instance_type" {
  description = "x86_64 EC2 control-plane instance type."
  type        = string
  default     = "t3a.medium"
}

variable "root_volume_gib" {
  description = "Encrypted gp3 root volume size."
  type        = number
  default     = 40

  validation {
    condition     = var.root_volume_gib >= 40
    error_message = "root_volume_gib must be at least 40."
  }
}

variable "integration_profile_volume_gib" {
  description = "Encrypted persistent MEGA and Patreon browser profile/state volume size."
  type        = number
  default     = 8

  validation {
    condition     = var.integration_profile_volume_gib >= 8
    error_message = "integration_profile_volume_gib must be at least 8."
  }
}

variable "postgres_engine_version" {
  description = "Pinned RDS PostgreSQL minor version."
  type        = string
  default     = "17.10"
}

variable "db_instance_class" {
  description = "Single-AZ RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gib" {
  description = "Initial encrypted gp3 RDS storage."
  type        = number
  default     = 20

  validation {
    condition     = var.db_allocated_storage_gib >= 20
    error_message = "db_allocated_storage_gib must be at least 20."
  }
}

variable "db_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "gen_automation"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.db_name))
    error_message = "db_name must be a valid lowercase PostgreSQL identifier."
  }
}

variable "db_master_username" {
  description = "RDS-managed bootstrap username; the password is generated by RDS."
  type        = string
  default     = "gen_automation_admin"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.db_master_username))
    error_message = "db_master_username must be a valid lowercase PostgreSQL identifier."
  }
}

variable "db_deletion_protection" {
  description = "Protect the staging database from deletion."
  type        = bool
  default     = true
}

variable "db_skip_final_snapshot" {
  description = "Skip the final RDS snapshot on destroy. Keep false for normal staging."
  type        = bool
  default     = false
}

variable "route53_zone_id" {
  description = "Optional existing Route53 public hosted-zone ID."
  type        = string
  default     = null
  nullable    = true
}

variable "hostname" {
  description = "Optional fully qualified hostname for the EIP A record and asset CORS origin."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.hostname == null
      || can(regex("^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$", var.hostname))
    )
    error_message = "hostname must be a lowercase fully qualified DNS name."
  }
}

variable "x_oauth_secret_arn" {
  description = "Optional existing complete X OAuth Secrets Manager secret ARN. Never pass secret JSON."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.x_oauth_secret_arn == null
      || can(regex("^arn:[^:]+:secretsmanager:[^:]+:[0-9]{12}:secret:.+$", var.x_oauth_secret_arn))
    )
    error_message = "x_oauth_secret_arn must be a complete Secrets Manager secret ARN."
  }
}

variable "notification_email" {
  description = "Operator email for the SNS alarm and monthly budget subscription."
  type        = string

  validation {
    condition     = can(regex("^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$", var.notification_email))
    error_message = "notification_email must be an email address."
  }
}

variable "monthly_budget_usd" {
  description = "Monthly AWS staging budget used for notification thresholds."
  type        = number
  default     = 100

  validation {
    condition     = var.monthly_budget_usd >= 10
    error_message = "monthly_budget_usd must be at least 10."
  }
}

variable "log_retention_days" {
  description = "CloudWatch application/bootstrap log retention."
  type        = number
  default     = 30
}

variable "tags" {
  description = "Additional non-sensitive AWS resource tags."
  type        = map(string)
  default     = {}
}
