variable "aws_region" {
  description = "AWS Region for staging."
  type        = string
  default     = "eu-central-1"
}

variable "name_prefix" {
  description = "Lowercase prefix used for resource names and globally unique bucket names."
  type        = string
  default     = "gen-automation-staging"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,29}$", var.name_prefix))
    error_message = "name_prefix must be 3-30 lowercase letters, digits, or hyphens."
  }
}

variable "vpc_cidr" {
  description = "Staging VPC IPv4 range."
  type        = string
  default     = "10.42.0.0/16"
}

variable "public_subnet_cidr" {
  description = "Public control-plane subnet IPv4 range."
  type        = string
  default     = "10.42.0.0/24"
}

variable "private_subnet_a_cidr" {
  description = "First private RDS subnet IPv4 range."
  type        = string
  default     = "10.42.10.0/24"
}

variable "private_subnet_b_cidr" {
  description = "Second private RDS subnet IPv4 range."
  type        = string
  default     = "10.42.11.0/24"
}

variable "http_ingress_cidrs" {
  description = "IPv4 clients allowed to reach public HTTP and HTTPS. SSH is never opened."
  type        = set(string)
  default     = ["0.0.0.0/0"]

  validation {
    condition     = length(var.http_ingress_cidrs) > 0
    error_message = "At least one HTTP/HTTPS ingress CIDR is required."
  }
}

variable "browser_upload_origin" {
  description = "Optional exact HTTPS dashboard origin allowed to upload directly to private S3 buckets."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.browser_upload_origin == null
      || can(regex("^https://[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?(?::[1-9][0-9]{0,4})?$", var.browser_upload_origin))
    )
    error_message = "browser_upload_origin must be one exact HTTPS origin without a path."
  }
}

variable "instance_type" {
  description = "x86_64 EC2 control-plane instance type."
  type        = string
  default     = "t3a.medium"
}

variable "root_volume_gib" {
  description = "Encrypted gp3 root volume size."
  type        = number
  default     = 40

  validation {
    condition     = var.root_volume_gib >= 40
    error_message = "root_volume_gib must be at least 40."
  }
}

variable "integration_profile_volume_gib" {
  description = "Encrypted persistent MEGA and Patreon browser profile/state volume size."
  type        = number
  default     = 8

  validation {
    condition     = var.integration_profile_volume_gib >= 8
    error_message = "integration_profile_volume_gib must be at least 8."
  }
}

variable "postgres_engine_version" {
  description = "Pinned RDS PostgreSQL minor version."
  type        = string
  default     = "17.10"
}

variable "db_instance_class" {
  description = "Single-AZ RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gib" {
  description = "Initial encrypted gp3 RDS storage."
  type        = number
  default     = 20

  validation {
    condition     = var.db_allocated_storage_gib >= 20
    error_message = "db_allocated_storage_gib must be at least 20."
  }
}

variable "db_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "gen_automation"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.db_name))
    error_message = "db_name must be a valid lowercase PostgreSQL identifier."
  }
}

variable "db_master_username" {
  description = "RDS-managed bootstrap username; the password is generated by RDS."
  type        = string
  default     = "gen_automation_admin"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.db_master_username))
    error_message = "db_master_username must be a valid lowercase PostgreSQL identifier."
  }
}

variable "db_deletion_protection" {
  description = "Protect the staging database from deletion."
  type        = bool
  default     = true
}

variable "db_skip_final_snapshot" {
  description = "Skip the final RDS snapshot on destroy. Keep false for normal staging."
  type        = bool
  default     = false
}

variable "route53_zone_id" {
  description = "Optional existing Route53 public hosted-zone ID."
  type        = string
  default     = null
  nullable    = true
}

variable "hostname" {
  description = "Optional fully qualified hostname for the EIP A record and asset CORS origin."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.hostname == null
      || can(regex("^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$", var.hostname))
    )
    error_message = "hostname must be a lowercase fully qualified DNS name."
  }
}

variable "x_oauth_secret_arn" {
  description = "Optional existing complete X OAuth Secrets Manager secret ARN. Never pass secret JSON."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.x_oauth_secret_arn == null
      || (
        var.x_oauth_auth_mode == "oauth2"
        && can(regex(
          "^arn:aws:secretsmanager:eu-central-1:861912887470:secret:gen-automation-staging/x/oauth-[A-Za-z0-9]{6}$",
          var.x_oauth_secret_arn
        ))
      )
      || (
        var.x_oauth_auth_mode == "oauth1"
        && can(regex(
          "^arn:aws:secretsmanager:eu-central-1:861912887470:secret:gen-automation-staging/x/oauth1-[A-Za-z0-9]{6}$",
          var.x_oauth_secret_arn
        ))
      )
    )
    error_message = "x_oauth_secret_arn must be the exact staging X secret ARN for x_oauth_auth_mode."
  }
}

variable "x_oauth_auth_mode" {
  description = "X user-context authentication mode. OAuth 1.0a credentials are static and read-only."
  type        = string
  default     = "oauth2"

  validation {
    condition     = contains(["oauth1", "oauth2"], var.x_oauth_auth_mode)
    error_message = "x_oauth_auth_mode must be oauth1 or oauth2."
  }
}

variable "civitai_api_secret_arn" {
  description = "Optional existing Civitai API-key Secrets Manager secret ARN. Never pass the API key itself."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.civitai_api_secret_arn == null
      || can(regex(
        "^arn:aws:secretsmanager:eu-central-1:861912887470:secret:gen-automation/staging/civitai-[A-Za-z0-9]{6}$",
        var.civitai_api_secret_arn
      ))
    )
    error_message = "civitai_api_secret_arn must be the exact staging Civitai API-key secret ARN."
  }
}

variable "salad_worker_artifact_object_versions" {
  description = "Exact model-bucket object keys and immutable S3 VersionIds readable by Salad workers. Empty disables the reader role; nonempty input must render within the role's 10,240-character aggregate inline-policy quota."
  type        = map(string)
  default     = {}

  validation {
    condition = (
      length(var.salad_worker_artifact_object_versions) <= 40
      && alltrue([
        for object_key, version_id in var.salad_worker_artifact_object_versions :
        can(regex(
          "^worker/((checkpoints|diffusion-models|loras|detectors|text-encoders|vae)/[A-Za-z0-9][A-Za-z0-9._/-]*|i2v/sha256/[0-9a-f]{64}|i2v/manifests/sha256/[0-9a-f]{64}\\.json)$",
          object_key,
        ))
        && !strcontains(object_key, "..")
        && !strcontains(object_key, "//")
        && !endswith(object_key, "/")
        && trimspace(version_id) != ""
        && version_id != "null"
        && length(version_id) <= 1024
      ])
    )
    error_message = "At most 40 artifact entries may use reviewed worker model, support-artifact, or I2V manifest keys and nonblank, non-null immutable VersionIds of at most 1,024 characters."
  }
}

variable "github_actions_deploy_enabled" {
  description = "Create a short-lived GitHub Actions OIDC role for main-branch deployments to the staging control plane."
  type        = bool
  default     = false
}

variable "github_actions_repository" {
  description = "Exact GitHub owner/repository allowed to deploy from refs/heads/main."
  type        = string
  default     = "neuraln-cyber/gen-automation"

  validation {
    condition = can(regex(
      "^[A-Za-z0-9][A-Za-z0-9_.-]{0,38}/[A-Za-z0-9][A-Za-z0-9_.-]{0,99}$",
      var.github_actions_repository,
    ))
    error_message = "github_actions_repository must be an exact GitHub owner/repository name without wildcards."
  }
}

variable "github_actions_repository_owner_id" {
  description = "Immutable numeric GitHub account ID for the repository owner used in the customized OIDC subject."
  type        = number
  default     = 310034173

  validation {
    condition = (
      var.github_actions_repository_owner_id > 0
      && floor(var.github_actions_repository_owner_id) == var.github_actions_repository_owner_id
    )
    error_message = "github_actions_repository_owner_id must be a positive integer."
  }
}

variable "github_actions_repository_id" {
  description = "Immutable numeric GitHub repository ID used in the customized OIDC subject."
  type        = number
  default     = 1314605368

  validation {
    condition = (
      var.github_actions_repository_id > 0
      && floor(var.github_actions_repository_id) == var.github_actions_repository_id
    )
    error_message = "github_actions_repository_id must be a positive integer."
  }
}

variable "github_actions_oidc_provider_arn" {
  description = "Optional existing IAM OIDC provider ARN for token.actions.githubusercontent.com. Leave null to manage one in this module when deployment is enabled."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.github_actions_oidc_provider_arn == null
      || can(regex(
        "^arn:[^:]+:iam::[0-9]{12}:oidc-provider/token\\.actions\\.githubusercontent\\.com$",
        var.github_actions_oidc_provider_arn,
      ))
    )
    error_message = "github_actions_oidc_provider_arn must be the complete IAM ARN for token.actions.githubusercontent.com."
  }
}

variable "notification_email" {
  description = "Operator email for the SNS alarm and monthly budget subscription."
  type        = string

  validation {
    condition     = can(regex("^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$", var.notification_email))
    error_message = "notification_email must be an email address."
  }
}

variable "monthly_budget_usd" {
  description = "Monthly AWS staging budget used for notification thresholds."
  type        = number
  default     = 100

  validation {
    condition     = var.monthly_budget_usd >= 10
    error_message = "monthly_budget_usd must be at least 10."
  }
}

variable "budget_enabled" {
  description = "Create the AWS budget in this account. Set false for an Organizations member account and create the linked-account budget in the management account instead."
  type        = bool
  default     = true
}

variable "abandoned_staging_retention_days" {
  description = "Days to retain abandoned presigned-upload objects under staging/. Immutable masters and durable outputs are never covered by this lifecycle rule."
  type        = number
  default     = 7

  validation {
    condition = (
      var.abandoned_staging_retention_days >= 1
      && var.abandoned_staging_retention_days <= 30
      && floor(var.abandoned_staging_retention_days) == var.abandoned_staging_retention_days
    )
    error_message = "abandoned_staging_retention_days must be a whole number from 1 through 30."
  }
}

variable "log_retention_days" {
  description = "CloudWatch application/bootstrap log retention."
  type        = number
  default     = 30
}

variable "tags" {
  description = "Additional non-sensitive AWS resource tags."
  type        = map(string)
  default     = {}
}
